# Generated by Django 2.0 on 2018-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20180221_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='arbitrariness_factor',
            field=models.PositiveSmallIntegerField(default=50, help_text='How arbitrary this hero is?'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='benevolence_factor',
            field=models.PositiveSmallIntegerField(default=50, help_text='How benevolent this hero is?'),
        ),
    ]
