# Generated by Django 2.0 on 2018-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20180326_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='villain_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
