# Generated by Django 2.0 on 2018-05-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0005_flexiblecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='flexiblecategory',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='FlexibleCategory',
        ),
    ]
